version: '3.8'
services:
  uwsgi:
    build:
      context: ./uwsgi
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    environment:
      - RABBITMQ_USER=guest
      - RABBITMQ_PASS=guest
      - RABBITMQ_PORT=5672
      - RABBITMQ_HOST=rabbitmq
    depends_on:
      - rabbitmq
    volumes:
      - .:/app # <- Работающий hot-reload

  worker:
    build:
      context: ./worker
      dockerfile: Dockerfile
    environment:
      - RABBITMQ_USER=guest
      - RABBITMQ_PASS=guest
      - RABBITMQ_PORT=5672
      - RABBITMQ_HOST=rabbitmq
    volumes:
      - ./worker/reports:/app/reports
    depends_on:
      - rabbitmq

  rabbitmq:
    image: rabbitmq:management
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbit_mqdata:/usr/share/rabbitmq/data
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://rabbitmq:15672" ]
      interval: 30s
      timeout: 5s
      retries: 5

volumes:
  rabbit_mqdata:
